### ISSUE TITLE
Negative sar_speedrun_offset values are converted to seconds incorrectly

### ISSUE THREAD

**Issue by SirWillian** [NeKzor/SourceAutoRecord#15]
The conversion from ticks to seconds is incorrect, as seen on the image below.
![image](https://user-images.githubusercontent.com/22877883/50808617-82ef2700-12e6-11e9-87cd-c248b8b16e95.png)

Does not cause timing innacuracies though.

**Comment by NeKzor** [comment]
I never had the intention to use the timer as a countdown. Is this really needed?

**Comment by SirWillian** [comment]
Not really needed. At least currently, there's no speedrun category that would use a countdown. Just figured I should report this somewhere
