### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by imgoodish** [NeKzor/SourceAutoRecord#17]
Portal 2, Windows 10. Has no problem loading the Chaos% plugin from chaos.dll in the same directory as sar.dll. 

```
] plugin_load sar
Unable to load plugin "sar"
Unable to load plugin "sar"

```

**Comment by NeKzor** [comment]
If this is the only console message you get then it means: The game could not find the file or SAR could not initialise the console.

Things you might want to check:
- Is sar.dll actually in the folder? (exact name)
- Has sar.dll been downloaded correctly? (odd file size)
- Are you using an antivirus? Is it blocking sar.dll?
- Does an older version of SAR work?

**Comment by imgoodish** [comment]
Guessing it was incorrectly downloaded the first time. Just redownloaded it and it worked first try. Thanks NeKz
