### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by sloast** [NeKzor/SourceAutoRecord#44]
sar.dll is in steamapps\common\Portal 2\portal2

`] plugin_load sar`
`Unable to load plugin "sar"`
`Unable to load plugin "sar"`

**Comment by NeKzor** [comment]
Looks like this has been resolved in the Portal 2 Speedrun Discord.

For people having similar problems:
- Make sure the plugin has been downloaded correctly
- Make sure to place the plugin where the game is installed
