### ISSUE TITLE
plugin_load sar crashing Portal2 on Linux

### ISSUE THREAD

**Issue by MortMyre** [NeKzor/SourceAutoRecord#48]
using 5.11.16-arch1-1 and have tried sar versions 1.09 and 1.12

When running `plugin_load sar`, the game freezes for a couple seconds and then crashes. Have tried reinstalling the binary and verifying file integrity via steam, but issue still persists. Happy to provide error logs if any exist.. I was unable to find any

**Comment by mlugg** [comment]
Hi,

Firstly, SAR versions 1.11 and above aren't primarily developed by NeKz anymore; they're maintained by Blenderiste09 and I on a different repo. Please open any future issues at https://github.com/p2sr/SourceAutoRecord - thanks!

In terms of this issue, 1.12 is an old version, which broke with some recent Portal 2 updates. You should use the latest version, 1.12.2.2. You can find that at https://github.com/Blenderiste09/SourceAutoRecord/releases/latest

**Comment by MortMyre** [comment]
My mistake, I was pointed to an old version from a video tutorial. 1.12.2.2 works for me. Thank you!!

**Comment by PortalRex** [comment]
Could you please link which video tutorial linked you to the old version? We will try and correct it.

**Comment by MortMyre** [comment]
https://www.youtube.com/watch?v=ZjQJmEPy50Y provided a link to 1.12, but not 1.12.2.2. his url uses /releases/tag/1.12 instead of /releases/tag/latest
